name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node LTS (20.x.x)
        uses: actions/setup-node@v4
        with:
          node-version: lts/Iron

      - name: npm install
        run: |
          npm ci --no-audit --no-fund

      - name: npm run build
        run: npm run build
        env:
          CI: true
