name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v6

      # https://github.com/marketplace/actions/setup-node-js-environment
      - name: Use Node LTS (24.x.x)
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          check-latest: true

      - name: npm install
        run: |
          npm ci --no-audit --no-fund

      - name: npm run build
        run: npm run build
        env:
          CI: true
